### ISSUE TITLE
Remove "Tester McGee" from contributors.js

### ISSUE THREAD

**Issue by GabeNedden** [GabeNedden/contribute#6]

**Comment by pranshuj73** [comment]
Can I be assigned to this issue?

**Comment by GabeNedden** [comment]
hey @pranshuj73 
It's all yours :smile:

**Comment by pranshuj73** [comment]
@GabeNedden do you mind if I work a bit more on the site and replace the dummy text?

**Comment by GabeNedden** [comment]
@pranshuj73 That'd be great! Please go ahead
